includes:
  - common: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.7.1/tasks/setup.yaml

tasks:
  - name: slim-cluster
    description: "Create a k3d cluster and deploy core slim dev"
    actions:
      - task: common:k3d-test-cluster

  - name: golangci
    description: "Install golangci-lint to GOPATH using install.sh"
    actions:
      - cmd: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
