includes:
  - setup: ./setup.yaml

tasks:
  - name: e2e-be
    actions:
      - task: setup:slim-cluster
      - cmd: go install github.com/air-verse/air@latest
      - description: "run air in the background"
        cmd: air -c .air.toml &

  - name: e2e-fe
    actions:
      - cmd: which playwright || npx playwright install
      - cmd: npm ci && npm run test:integration
        dir: ui

  - name: go
    actions:
      - cmd: go test -failfast -v -timeout 30m ./...

  - name: frontend-unit
    actions:
      - cmd: npm ci && npm run test:unit
        dir: ui

  - name: unit
    actions:
      - task: go
      - task: frontend-unit
