includes:
  - setup: ./setup.yaml

tasks:
  - name: e2e
    actions:
      - task: setup:slim-cluster
      - cmd: go install github.com/air-verse/air@latest
      - cmd: which playwright || npx playwright install
      - cmd: air -c .air.toml &
      - cmd: npm ci && npm run test:integration
        dir: ui

  - name: go
    actions:
      - cmd: go test -failfast -v -timeout 30m ./...

  - name: frontend-unit
    actions:
      - cmd: npm ci && npm run test:unit
        dir: ui

  - name: unit
    actions:
      - task: go
      - task: frontend-unit
