includes:
  - setup: ./setup.yaml

tasks:
  - name: frontend-unit
    actions:
      - task: setup:node_modules
      - cmd: npm run test:unit
        dir: ui

  - name: e2e
    actions:
      - task: setup:node_modules
      - cmd: which playwright || npx playwright install
      - task: setup:slim-cluster
      - cmd: npm run test:integration
        dir: ui

  - name: stream
    actions:
      - cmd: go test -failfast -v -timeout 30m
        dir: pkg/stream

  - name: pepr
    actions:
      - cmd: go test -failfast -v -timeout 30m
        dir: pkg/pepr

  - name: unit
    actions:
      - task: stream
      - task: pepr
      - task: frontend-unit
