variables:
  - name: STATE_BUCKET
    description: "Name of the S3 bucket to store Terraform state"
    default: runtime-tf-state

  - name: REGION
    description: "AWS region to deploy resources"
    default: us-east-1

  - name: DYNAMO_TABLE
    description: "Name of the DynamoDB table to store Terraform locks"
    default: runtimte-tf-state-lock

tasks:
  - name: create-backend
    actions:
      - description: Create State Bucket and DynamoDB Table (requies aws cli and terminal authenticated to aws account)
        cmd: |
          echo "[*] Creating TF Backend in AWS..."
          aws s3 ls --summarize --region us-east-1 ${STATE_BUCKET} &>/dev/null || \
              aws s3api create-bucket \
                  --bucket ${STATE_BUCKET} \
                  --region ${REGION} && \
              aws s3api put-bucket-versioning \
                  --bucket ${STATE_BUCKET} \
                  --versioning-configuration Status=Enabled
          aws dynamodb describe-table --region ${REGION} --table-name ${DYNAMO_TABLE} &>/dev/null || \
              aws dynamodb create-table \
                --table-name ${DYNAMODB_TABLE} \
                --attribute-definitions AttributeName=LockID,AttributeType=S \
                --key-schema AttributeName=LockID,KeyType=HASH \
                --billing-mode PAY_PER_REQUEST \
                --region ${REGION}
        shell:
          linux: "bash"

  - name: create-infra
    description: "spinup runtime test infra (requires aws cli and terminal authenticated to aws account)"
    actions:
      - cmd: |
          tofu -chdir=../terraform init -reconfigure \
            -backend-config="bucket=${STATE_BUCKET}" \
            -backend-config="key=tfstate/runtime.tfstate" \
            -backend-config="region=${REGION}" \
            -backend-config="dynamodb_table=${DYNAMODB_TABLE}" \
            -backend-config="encrypt=true"

          tofu -chdir=../terraform apply -auto-approve

  - name: destroy-infra
    description: "destroy runtime test infra (requires aws cli and terminal authenticated to aws account)"
    actions:
      - cmd: |
          tofu -chdir=test-infra/terraform destroy -auto-approve
