variables:
  - name: REGION
  - name: STATE_BUCKET
  - name: STATE_DYNAMO_TABLE
  - name: STATE_KEY

tasks:
  - name: create-iac
    description: "spinup runtime test infra"
    actions:
      - cmd: echo ${STATE_KEY} | sed 's/\.tfstate/-buckets1.tfstate/g'
        setVariables:
          - name: BUCKETS_STATE_KEY
      - cmd: |
          tofu init -force-copy \
          -backend-config="bucket=${STATE_BUCKET}" \
          -backend-config="key=${BUCKETS_STATE_KEY}" \
          -backend-config="region=${REGION}" \
          -backend-config="dynamodb_table=${DYNAMODB_TABLE}"
        dir: .github/test-infra/terraform
      - cmd: terraform apply -auto-approve
        dir: .github/test-infra/terraform

  - name: destroy-iac
    description: "destroy runtime test infra"
    actions:
      - cmd: tofu destroy -auto-approve
        dir: .github/test-infra/terraform
