name: Nightly Release
on:
  workflow_dispatch:
  # todo: remove pull_request block
  pull_request:
    branches: [ main ]
    types: [ milestoned, opened, edited, synchronize ]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - "goreleaser.yml"
  schedule:
    - cron: "0 3 * * *" ## nightly at 3am UTC

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/pr-tests.yaml

  push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-tags: 'true'

      - name: Login to GHCR
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup Environment (Go, Node, Homebrew, UDS CLI, k3d)
        uses: ./.github/actions/setup

      - name: Publish
        run: |
          uds run build:publish-uds-runtime

      - name: Update nightly-unstable tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          # cleanup old release
          gh release delete nightly-unstable --cleanup-tag -y || true
          # generate new release
          gh release create nightly-unstable ./build/zarf-package-uds-runtime-* \
            -t "nightly-unstable" \
            --prerelease \
            -n 'Nightly unstable build'
