name: PR
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - "goreleaser.yml"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [unit, e2e]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 21.1.0

      - name: Setup k3d
        uses: ./.github/actions/k3d

      - name: Run unit tests
        run: uds run test:${{ matrix.type }} --no-progress

      - name: Debug Output
        if: ${{ matrix.type == 'e2e'}}
        uses: defenseunicorns/uds-common/.github/actions/debug-output@772b3337950b7c8e0882c527263684306bba7ce4 # v0.7.1

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@772b3337950b7c8e0882c527263684306bba7ce4 # v0.7.1
        with:
          suffix: ${{ matrix.type }}
