name: Validate Lint
on: pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Install golangci-lint
        run: uds run setup:golangci --no-progress

      - name: Run pre-commit
        uses: pre-commit/action@f7acafac0271bdd064cdfa1b13f17b4350e565ed #
        with:
          extra_args: --all-files --verbose # pre-commit run --all-files --verbose

      - name: Run prettier and eslint
        run: uds run lint:ui --no-progress
