name: Validate Lint
on: pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install UDS CLI
        uses: ./.github/actions/install-uds-cli

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Install golangci-lint
        run: uds run setup:golangci --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 21.1.0

      # build ui so ui/build exists when pre-commit runs
      - name: build-ui
        run: uds run build-ui --no-progress

      - name: Run pre-commit
        uses: pre-commit/action@f7acafac0271bdd064cdfa1b13f17b4350e565ed #
        with:
          extra_args: --all-files --verbose # pre-commit run --all-files --verbose

      - name: Lint Yaml
        run: uds run lint:yaml --no-progress

      - name: Lint UI
        run: uds run lint:ui --no-progress
